/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoListRouteImport } from './routes/todo-list'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GadgetClassifierRouteImport } from './routes/gadget-classifier'
import { Route as IndexRouteImport } from './routes/index'

const TodoListRoute = TodoListRouteImport.update({
  id: '/todo-list',
  path: '/todo-list',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GadgetClassifierRoute = GadgetClassifierRouteImport.update({
  id: '/gadget-classifier',
  path: '/gadget-classifier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gadget-classifier': typeof GadgetClassifierRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/todo-list': typeof TodoListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gadget-classifier': typeof GadgetClassifierRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/todo-list': typeof TodoListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gadget-classifier': typeof GadgetClassifierRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/todo-list': typeof TodoListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gadget-classifier' | '/login' | '/map' | '/todo-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gadget-classifier' | '/login' | '/map' | '/todo-list'
  id: '__root__' | '/' | '/gadget-classifier' | '/login' | '/map' | '/todo-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GadgetClassifierRoute: typeof GadgetClassifierRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  TodoListRoute: typeof TodoListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todo-list': {
      id: '/todo-list'
      path: '/todo-list'
      fullPath: '/todo-list'
      preLoaderRoute: typeof TodoListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gadget-classifier': {
      id: '/gadget-classifier'
      path: '/gadget-classifier'
      fullPath: '/gadget-classifier'
      preLoaderRoute: typeof GadgetClassifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GadgetClassifierRoute: GadgetClassifierRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  TodoListRoute: TodoListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
